# Generated by Django 5.2.6 on 2025-10-03 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('evaluation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TirePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_code', models.CharField(max_length=50, unique=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('load_index', models.CharField(max_length=10)),
                ('speed_symbol', models.CharField(max_length=5)),
                ('road_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TirePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
                ('axle_number', models.IntegerField()),
                ('wheel_number', models.IntegerField()),
                ('is_spare', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TireStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Truck'), ('TRAILER', 'Trailer'), ('BUS', 'Bus'), ('VAN', 'Van')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance')], default='ACTIVE', max_length=20)),
                ('tire_configuration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_tread_depth', models.DecimalField(decimal_places=2, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tires.supplier')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tires.tirepattern')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tires.tirestatus')),
            ],
        ),
        migrations.CreateModel(
            name='TireInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_odometer', models.IntegerField()),
                ('driver_id', models.CharField(blank=True, max_length=50)),
                ('tread_depth', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tire_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommended_action', models.CharField(choices=[('OK', 'OK - No Action Needed'), ('ROTATE', 'Rotate Tire'), ('REPAIR', 'Repair Needed'), ('REPLACE', 'Replace Tire'), ('PRESSURE_ADJUST', 'Adjust Pressure')], max_length=20)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='tires.employee')),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='tires.tire')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.tireposition')),
            ],
        ),
        migrations.AddField(
            model_name='tireposition',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_positions', to='tires.vehicle'),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_id', models.CharField(max_length=50, unique=True)),
                ('service_date', models.DateField()),
                ('service_mileage', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tires.servicetype')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_services', to='tires.supplier')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='tires.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('current_mileage', models.IntegerField()),
                ('shift_type', models.CharField(choices=[('INSTALLATION', 'Tire Installation'), ('REMOVAL', 'Tire Removal'), ('ROTATION', 'Tire Rotation'), ('REPAIR', 'Tire Repair')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='tires.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='tires.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TireAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('removal_date', models.DateField(blank=True, null=True)),
                ('start_odometer', models.IntegerField()),
                ('end_odometer', models.IntegerField(blank=True, null=True)),
                ('removal_mileage', models.IntegerField(blank=True, null=True)),
                ('reason_for_removal', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tire_assignments', to='tires.employee')),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tires.tire')),
                ('from_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_from', to='tires.tireposition')),
                ('to_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_to', to='tires.tireposition')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_assignments', to='tires.workorder')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tireposition',
            unique_together={('vehicle', 'axle_number', 'wheel_number')},
        ),
    ]
