# Generated by Django 5.2.7 on 2025-11-01 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('evaluation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TirePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_code', models.CharField(max_length=50, unique=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=50)),
                ('load_index', models.CharField(max_length=10)),
                ('speed_symbol', models.CharField(max_length=5)),
                ('road_type', models.CharField(max_length=50)),
                ('axle_type', models.CharField(default='DRIVE', max_length=50)),
                ('initial_tread_depth', models.DecimalField(decimal_places=2, default=15.0, max_digits=4)),
                ('discarding_tread_depth', models.DecimalField(decimal_places=2, default=3.0, max_digits=4)),
                ('ideal_tire_pressure', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TireStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TireWearType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wear_common_cause', models.CharField(max_length=50)),
                ('recovery_scheme', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Truck'), ('TRAILER', 'Trailer'), ('BUS', 'Bus'), ('VAN', 'Van')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance')], default='ACTIVE', max_length=20)),
                ('tire_configuration', models.CharField(max_length=100)),
                ('odometer', models.IntegerField(default=0)),
                ('number_of_or_tires', models.IntegerField(default=0)),
                ('number_of_sp_tires', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_tread_depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tires.supplier')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tires.tirepattern')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tires.tirestatus')),
            ],
        ),
        migrations.CreateModel(
            name='TirePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
                ('axle_number', models.IntegerField()),
                ('wheel_number', models.IntegerField()),
                ('axle_type', models.CharField(choices=[('STEERING', 'Steering Axle'), ('DRIVE', 'Drive Axle'), ('TRAILER', 'Trailer Axle'), ('LIFTABLE', 'Liftable Axle')], default='DRIVE', max_length=20)),
                ('tire_order', models.IntegerField(default=1)),
                ('is_spare', models.BooleanField(default=False)),
                ('mounted_tire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mounted_positions', to='tires.tire')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_positions', to='tires.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'axle_number', 'wheel_number')},
            },
        ),
        migrations.CreateModel(
            name='TireInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_odometer', models.IntegerField()),
                ('tread_depth', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consumption_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('remaining_traveling_distance', models.IntegerField(default=0)),
                ('cost_per_mm_tread_depth', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cost_per_1000_km_travel', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fuel_consumption_increase', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fuel_loss_caused', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('current_tire_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('balance_traveling_distance', models.IntegerField(default=0)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='tires.employee')),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='tires.tire')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.tireposition')),
                ('wear_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tires.tireweartype')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_mileage', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tires.servicetype')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_services', to='tires.supplier')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='tires.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('driver_id', models.CharField(blank=True, max_length=50)),
                ('current_odometer', models.IntegerField()),
                ('shift_type', models.CharField(choices=[('INSPECTION', 'Tire Inspection'), ('ASSIGNMENT', 'Tire Assignment')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OPENED', 'Opened'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='tires.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='tires.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TireAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('removal_date', models.DateField(blank=True, null=True)),
                ('reason_for_removal', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tires.tire')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='tires.tireinspection')),
                ('tire_position_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_from', to='tires.tireposition')),
                ('tire_position_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_to', to='tires.tireposition')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_assignments', to='tires.workorder')),
            ],
        ),
    ]
