# Generated by Django 5.2.7 on 2025-10-10 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='maintenance_id',
        ),
    ]
