# Generated by Django 5.2.7 on 2025-11-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0002_alter_tireinspection_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireinspection',
            name='tread_depth',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
