# Generated by Django 5.2.7 on 2025-10-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0002_remove_maintenancerecord_maintenance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='initial_tread_depth',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
