# Generated by Django 5.2.7 on 2025-10-17 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0003_alter_tire_initial_tread_depth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireWearType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear_type', models.CharField(max_length=50)),
                ('wear_common_cause', models.CharField(max_length=50)),
                ('recovery_scheme', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tireinspection',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='tireinspection',
            name='inspection_date',
        ),
        migrations.RemoveField(
            model_name='tireinspection',
            name='recommended_action',
        ),
        migrations.RemoveField(
            model_name='tireinspection',
            name='tire_consumption',
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='balance_traveling_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='consumption_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='cost_per_1000_km_travel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='cost_per_mm_tread_depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='current_tire_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='fuel_consumption_increase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='fuel_loss_caused',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='remaining_traveling_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='wear_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='tires.tireweartype'),
            preserve_default=False,
        ),
    ]
