# Generated by Django 5.2.7 on 2025-10-17 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0003_alter_tire_initial_tread_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tireassignment',
            name='inspector',
        ),
        migrations.AddField(
            model_name='tireassignment',
            name='tire_inspection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tire_assignments', to='tires.tireinspection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tireassignment',
            name='assignment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tireassignment',
            name='end_odometer',
            field=models.IntegerField(default=94832),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tireassignment',
            name='from_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_from', to='tires.tireposition'),
        ),
        migrations.AlterField(
            model_name='tireassignment',
            name='reason_for_removal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tireassignment',
            name='removal_mileage',
            field=models.IntegerField(default=4839),
            preserve_default=False,
        ),
    ]
