# Generated by Django 5.2.7 on 2025-10-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0004_tireweartype_remove_tireinspection_driver_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tireweartype',
            old_name='wear_type',
            new_name='name',
        ),
    ]
