# Generated by Django 5.2.7 on 2025-10-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0005_alter_tire_initial_tread_depth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tireassignment',
            old_name='from_position',
            new_name='tire_position_from',
        ),
        migrations.RenameField(
            model_name='tireassignment',
            old_name='to_position',
            new_name='tire_position_to',
        ),
    ]
