# Generated by Django 5.2.7 on 2025-10-17 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0005_rename_wear_type_tireweartype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='current_mileage',
            new_name='current_odometer',
        ),
        migrations.AddField(
            model_name='tireassignment',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='tires.tireinspection'),
        ),
        migrations.AddField(
            model_name='tirepattern',
            name='axle_type',
            field=models.CharField(default='DRIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='tirepattern',
            name='discarding_tread_depth',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='tirepattern',
            name='ideal_tire_pressure',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tirepattern',
            name='initial_tread_depth',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='tireposition',
            name='axle_type',
            field=models.CharField(choices=[('STEERING', 'Steering Axle'), ('DRIVE', 'Drive Axle'), ('TRAILER', 'Trailer Axle'), ('LIFTABLE', 'Liftable Axle')], default='DRIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='tireposition',
            name='hounded_tire_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tireposition',
            name='tire_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='number_of_or_tires',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='number_of_sp_tires',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='driver_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
