# Generated by Django 5.2.7 on 2025-10-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0006_rename_current_mileage_workorder_current_odometer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tireassignment',
            old_name='from_position',
            new_name='tire_position_from',
        ),
        migrations.RenameField(
            model_name='tireassignment',
            old_name='to_position',
            new_name='tire_position_to',
        ),
        migrations.RemoveField(
            model_name='tireassignment',
            name='inspector',
        ),
    ]
