# Generated by Django 5.2.7 on 2025-10-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0006_rename_from_position_tireassignment_tire_position_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tireassignment',
            name='tire_inspection',
        ),
    ]
