# Generated by Django 5.2.7 on 2025-10-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0006_rename_current_mileage_workorder_current_odometer_and_more'),
        ('tires', '0007_remove_tireassignment_tire_inspection'),
    ]

    operations = [
    ]
