# Generated by Django 5.2.7 on 2025-10-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0007_rename_from_position_tireassignment_tire_position_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='shift_type',
            field=models.CharField(choices=[('INSPECTION', 'Tire Inspection'), ('ASSIGNMENT', 'Tire Assignment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OPENED', 'Opened'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='PENDING', max_length=20),
        ),
    ]
