# Generated by Django 5.2.7 on 2025-10-18 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0008_alter_workorder_shift_type_alter_workorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tireposition',
            name='hounded_tire_id',
        ),
        migrations.AddField(
            model_name='tireposition',
            name='mounted_tire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mounted_positions', to='tires.tire'),
        ),
    ]
