# Generated by Django 5.2.7 on 2025-10-19 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0009_remove_tireposition_hounded_tire_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tireassignment',
            name='end_odometer',
        ),
        migrations.RemoveField(
            model_name='tireassignment',
            name='removal_mileage',
        ),
        migrations.RemoveField(
            model_name='tireassignment',
            name='start_odometer',
        ),
    ]
