# Generated by Django 5.2.7 on 2025-11-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0010_remove_tireassignment_end_odometer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireinspection',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='tires.tireposition'),
        ),
    ]
