# Generated by Django 5.2.7 on 2025-11-19 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0011_alter_tireinspection_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='last_pressure',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='last_tread_depth',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tire_inspections', to='tires.workorder'),
        ),
        migrations.AlterField(
            model_name='tireinspection',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.tireposition'),
        ),
    ]
