# Generated by Django 5.2.7 on 2025-11-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0012_tire_last_pressure_tire_last_tread_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
