# Generated by Django 5.2.7 on 2025-12-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0012_tire_last_pressure_tire_last_tread_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ImportStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SESSION_ID', models.CharField(db_index=True, max_length=100)),
                ('MODEL_TYPE', models.CharField(choices=[('employee', 'Employee'), ('vehicle', 'Vehicle'), ('workorder', 'Work Order'), ('maintenance_record', 'Maintenance Record'), ('tire_assignment', 'Tire Assignment'), ('tire_inspection', 'Tire Inspection'), ('service_type', 'Service Type'), ('supplier', 'Supplier'), ('tire_wear_type', 'Tire Wear Type'), ('tire_status', 'Tire Status')], max_length=50)),
                ('ROW_NUMBER', models.IntegerField()),
                ('DATA', models.JSONField()),
                ('STATUS', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('imported', 'Imported')], default='pending', max_length=20)),
                ('ERROR_MESSAGE', models.TextField(blank=True, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'import_staging',
                'ordering': ['SESSION_ID', 'ROW_NUMBER'],
                'indexes': [models.Index(fields=['SESSION_ID'], name='import_stag_SESSION_325f02_idx'), models.Index(fields=['MODEL_TYPE'], name='import_stag_MODEL_T_440212_idx'), models.Index(fields=['STATUS'], name='import_stag_STATUS_59d009_idx')],
            },
        ),
    ]
