# Generated by Django 5.2.7 on 2025-12-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0013_alter_workorder_cost_importstaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importstaging',
            name='DATA',
            field=models.JSONField(default=dict),
        ),
    ]
