# Generated by Django 5.2.7 on 2025-11-26 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0013_alter_workorder_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tirepattern',
            name='brand_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tire_patterns', to='tires.supplier'),
        ),
    ]
