# Generated by Django 5.2.7 on 2025-12-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0014_alter_importstaging_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importstaging',
            options={'verbose_name': 'Import Staging', 'verbose_name_plural': 'Import Staging'},
        ),
        migrations.RemoveIndex(
            model_name='importstaging',
            name='import_stag_SESSION_325f02_idx',
        ),
        migrations.RemoveIndex(
            model_name='importstaging',
            name='import_stag_MODEL_T_440212_idx',
        ),
        migrations.RemoveIndex(
            model_name='importstaging',
            name='import_stag_STATUS_59d009_idx',
        ),
        migrations.RenameField(
            model_name='importstaging',
            old_name='CREATED_AT',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='importstaging',
            name='UPDATED_AT',
        ),
        migrations.AlterField(
            model_name='importstaging',
            name='MODEL_TYPE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='importstaging',
            name='SESSION_ID',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='importstaging',
            name='STATUS',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('imported', 'Imported')], default='pending', max_length=20),
        ),
    ]
