# Generated by Django 5.2.7 on 2025-12-08 16:15

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0015_alter_importstaging_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('import_type', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField()),
                ('approved_rows', models.IntegerField()),
                ('imported_rows', models.IntegerField()),
                ('failed_rows', models.IntegerField()),
                ('import_duration', models.IntegerField(help_text='Duration in seconds')),
                ('stats', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Detailed statistics (records created, linked, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Inspection Report v2')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this template does', null=True)),
                ('import_type', models.CharField(choices=[('inventory', 'Tire Inventory'), ('inspection', 'Tire Inspection'), ('assignment', 'Tire Assignment'), ('maintenance', 'Maintenance Record'), ('custom', 'Custom')], db_index=True, max_length=50)),
                ('mapping_rules', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Column -> Field mapping rules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='Allow other users to use this template')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
            ],
            options={
                'verbose_name': 'Import Template',
                'verbose_name_plural': 'Import Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='importstaging',
            options={'ordering': ['SESSION_ID', 'ROW_NUMBER'], 'verbose_name': 'Import Staging', 'verbose_name_plural': 'Import Staging'},
        ),
        migrations.RenameField(
            model_name='importstaging',
            old_name='created_at',
            new_name='CREATED_AT',
        ),
        migrations.AddField(
            model_name='importstaging',
            name='CREATED_RECORD_ID',
            field=models.CharField(blank=True, help_text='ID of created database record', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='importstaging',
            name='UPDATED_AT',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='importstaging',
            name='DATA',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Raw row data from spreadsheet'),
        ),
        migrations.AlterField(
            model_name='importstaging',
            name='ERROR_MESSAGE',
            field=models.TextField(blank=True, help_text='Error details if import failed', null=True),
        ),
        migrations.AlterField(
            model_name='importstaging',
            name='MODEL_TYPE',
            field=models.CharField(choices=[('inventory', 'Tire Inventory'), ('inspection', 'Tire Inspection'), ('assignment', 'Tire Assignment'), ('maintenance', 'Maintenance Record'), ('custom', 'Custom')], max_length=50),
        ),
        migrations.AlterField(
            model_name='importstaging',
            name='SESSION_ID',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='importstaging',
            name='STATUS',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('imported', 'Imported')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='importstaging',
            index=models.Index(fields=['SESSION_ID', 'STATUS'], name='tires_impor_SESSION_65d5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='importstaging',
            index=models.Index(fields=['MODEL_TYPE', 'STATUS'], name='tires_impor_MODEL_T_5b3be5_idx'),
        ),
        migrations.AlterModelTable(
            name='importstaging',
            table=None,
        ),
        migrations.AddField(
            model_name='importlog',
            name='imported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importtemplate',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this template', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importlog',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tires.importtemplate'),
        ),
        migrations.AddIndex(
            model_name='importtemplate',
            index=models.Index(fields=['import_type', 'is_public'], name='tires_impor_import__66930a_idx'),
        ),
        migrations.AddIndex(
            model_name='importtemplate',
            index=models.Index(fields=['created_by', '-created_at'], name='tires_impor_created_a26e2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importtemplate',
            unique_together={('name', 'created_by')},
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['import_type', '-created_at'], name='tires_impor_import__5c2c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['imported_by', '-created_at'], name='tires_impor_importe_0dfd4e_idx'),
        ),
    ]
