# Generated by Django 5.2.7 on 2025-12-19 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0002_tireassignment_is_discard_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='last_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_for_tire', to='tires.tireassignment'),
        ),
        migrations.AlterField(
            model_name='tireassignment',
            name='tire_position_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_to', to='tires.tireposition'),
        ),
    ]
